version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - prometheus
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5000/ || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 3
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
